### ISSUE TITLE
Change char * settings to int in settings.c

### ISSUE THREAD

**Issue by GaelleMarais** [Kagamihime/VIlain#81]
Hi,
@DavidVn64  : Do you have an exemple of a file you can load with the function `int load(SETTINGS * sets, char *path)` in `settings.c` ? 
I've been trying to use it but I don't understand what the config file should looks like. I guess you have created one to visualise your code, can I see it please ?

**Comment by DavidVn64** [comment]
Sure here is the content of a typical example of a ui.cfg file.

```
line_wrapping: 1
save_shortcut: ctrl+s
load_shortcut: ctrl+l
settings_shortcut: ctrl+p
copy_shortcut: ctrl+c
cut_shortcut: ctrl+x
paste_shortcut: ctrl+v
toggle_selection_shortcut: ctrl+t
```

**Comment by GaelleMarais** [comment]
Alright thanks!
The problem is that with ncurses, keys are identified with `int`, for example to get the key pressed by the user I use `getch()` and get the ascii code of the key that is pressed.
So we need to change the `settings` module because the lines in the config file should look like : 
`save_shortcut: 19` 
Because 19 is the ascii code for ctrl+s

I would like you tu change the type for that please, and sorry to not have considered that problem  before

**Comment by Kagamihime** [comment]
I think it is better to store the short cuts with the form "ctrl+<letter>" in the configuration file because it is human readable and there would be a better portability.
However, whether such a function to translate between the ASCII code and the string should live in the ui or the settings, is up to you ^^

**Comment by DavidVn64** [comment]
Ok I will try to modify it in order to give you a structure filled with the ASCII code for each shortcut instead of a simple string

**Comment by DavidVn64** [comment]
Well isn't the point of the Ascii table to be "bijectionnal" ? like for an ascii code, there is a unique meaning and vice versa ?
If yes, we only need to make 2 functions to get an ascii code from a String that you will use in your function to change the settings when the user wants to; and the opposite when you want to fill the file to be more human readable.
But you're right about the robustness of the functions, because indeed if the user decides to change manually the ui.cfg file, the program will probably have bugs or even crash.

**Comment by DavidVn64** [comment]
I will try to do it, but honestly I'm really busy right now with the exams next week and the projects in the other classes.
