### ISSUE TITLE
Write tests for the module "io_text"

### ISSUE THREAD

**Issue by Kagamihime** [Kagamihime/VIlain#85]
We should write tests for each functions of the API of the module "io_text".
Any bugs discovered during this process should be fixed.

I guess that @DavidVn64 could also do this because he implemented it too.

**Comment by DavidVn64** [comment]
@Kagamihime Can you tell me more details about your functions please ? 
Because in order to test load_file, I am using `insert_line(buff, "", 0)`, then I am saving it in a file with save_buffer and loading it in a second BUFFER *buff2, then I use str = get_line(buff2, 0) and compare it to "", it should assert true, right ?

**Comment by Kagamihime** [comment]
No, because there is a new line at the end of all lines, so the file should have have "\n" in its content

**Comment by DavidVn64** [comment]
Oh yes I thought about that but even `ck_assert_ptr_eq(str, "\n")` does not work

**Comment by Kagamihime** [comment]
I don't know... It took my hours to write my tests/debug the buffer module ^^'
So it's not very useful to do that on the last day before the end of the project :/

**Comment by DavidVn64** [comment]
It was actually dumb, I used ptr instead of str
